# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate pnet

Name:           rust-pnet
Version:        0.34.0
Release:        %autorelease
Summary:        Cross-platform, low level networking using the Rust programming language

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/pnet
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Cross-platform, low level networking using the Rust programming
language.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+appveyor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+appveyor-devel %{_description}

This package contains library source intended for building other packages which
use the "appveyor" feature of the "%{crate}" crate.

%files       -n %{name}+appveyor-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+benchmark-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+benchmark-devel %{_description}

This package contains library source intended for building other packages which
use the "benchmark" feature of the "%{crate}" crate.

%files       -n %{name}+benchmark-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ipnetwork-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ipnetwork-devel %{_description}

This package contains library source intended for building other packages which
use the "ipnetwork" feature of the "%{crate}" crate.

%files       -n %{name}+ipnetwork-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+netmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+netmap-devel %{_description}

This package contains library source intended for building other packages which
use the "netmap" feature of the "%{crate}" crate.

%files       -n %{name}+netmap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pcap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pcap-devel %{_description}

This package contains library source intended for building other packages which
use the "pcap" feature of the "%{crate}" crate.

%files       -n %{name}+pcap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pnet_datalink-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pnet_datalink-devel %{_description}

This package contains library source intended for building other packages which
use the "pnet_datalink" feature of the "%{crate}" crate.

%files       -n %{name}+pnet_datalink-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pnet_sys-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pnet_sys-devel %{_description}

This package contains library source intended for building other packages which
use the "pnet_sys" feature of the "%{crate}" crate.

%files       -n %{name}+pnet_sys-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pnet_transport-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pnet_transport-devel %{_description}

This package contains library source intended for building other packages which
use the "pnet_transport" feature of the "%{crate}" crate.

%files       -n %{name}+pnet_transport-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+travis-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+travis-devel %{_description}

This package contains library source intended for building other packages which
use the "travis" feature of the "%{crate}" crate.

%files       -n %{name}+travis-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
