# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate elf

Name:           rust-elf
Version:        0.7.4
Release:        %autorelease
Summary:        Pure-rust library for parsing ELF files

%global forgeurl https://github.com/cole14/%{name}
%global tag v%{version}
%forgemeta

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/elf
Source0:        %{crates_source}
# Source coming from upstream forge only used for testing.
Source1:        %forgesource

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A pure-rust library for parsing ELF files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYRIGHT
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nightly-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nightly-devel %{_description}

This package contains library source intended for building other packages which
use the "nightly" feature of the "%{crate}" crate.

%files       -n %{name}+nightly-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+to_str-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+to_str-devel %{_description}

This package contains library source intended for building other packages which
use the "to_str" feature of the "%{crate}" crate.

%files       -n %{name}+to_str-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
tar xf %{SOURCE1} --strip-components=1 %{topdir}/sample-objects
%check
%cargo_test
%endif

%changelog
%autochangelog
