# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate derive-into-owned

Name:           rust-derive-into-owned
Version:        0.2.0
Release:        %autorelease
Summary:        Custom derives to help with types containing Cow fields

License:        MIT
URL:            https://crates.io/crates/derive-into-owned
Source:         %{crates_source}
# https://github.com/koivunej/derive-into-owned/issues/19
Source:         https://github.com/koivunej/derive-into-owned/raw/master/LICENSE

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Custom derives to help with types containing Cow fields.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
cp %{SOURCE1} .

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
