# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate pnet_datalink

Name:           rust-pnet_datalink
Version:        0.34.0
Release:        %autorelease
Summary:        Cross-platform, datalink layer networking

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/pnet_datalink
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          pnet_datalink-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Cross-platform, datalink layer networking.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+netmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+netmap-devel %{_description}

This package contains library source intended for building other packages which
use the "netmap" feature of the "%{crate}" crate.

%files       -n %{name}+netmap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+netmap_sys-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+netmap_sys-devel %{_description}

This package contains library source intended for building other packages which
use the "netmap_sys" feature of the "%{crate}" crate.

%files       -n %{name}+netmap_sys-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pcap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pcap-devel %{_description}

This package contains library source intended for building other packages which
use the "pcap" feature of the "%{crate}" crate.

%files       -n %{name}+pcap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
