# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate byteorder_slice

Name:           rust-byteorder_slice
Version:        3.0.0
Release:        %autorelease
Summary:        Byteorder like crate for &[u8]

License:        MIT
URL:            https://crates.io/crates/byteorder_slice
Source:         %{crates_source}
# Add license text as this is missing upstream:
# https://github.com/courvoif/byteorder_slice/pull/4
Patch:          byteorder_slice-add-mit-license-file.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Byteorder like crate for &[u8].}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
